.TH spanner\-config 1 2014\-11\-25
.SH NAME
.B
spanner-config
 \-  spanner config 

Display the current configuration

.SH SYNOPSIS
spanner config 
.SH DESCRIPTION
 spanner config 

Display the current configuration

.SH SEEALSO
 spanner help <subcommand> 
.SH BUGS
 file issues or bugs
.UR
https://opensource.sas.com/its
 
.SH AUTHORS
.B
 spanner
was written by SAS
.UR
http://www.sas.com/
.
.SH COPYRIGHT
 Copyright (c)
.B
SAS Institute Inc.
 
