.TH spanner\-plan 1 2014\-11\-25
.SH NAME
.B
spanner-plan
 \-  spanner plan [uri]

Create bob-plans templates from wms

.SH SYNOPSIS
 spanner plan [uri]
.SH DESCRIPTION
 spanner plan [uri]

Build bob\-plans from wms

.SH OPTIONS
.TP
.B \-\-branch=BRANCH

.TP
.B \-\-cfgfile=CFGFILE

.TP
.B \-\-debug\-logging

.TP
.B \-\-dry\-run

.TP
.B \-\-quiet

.SH SEEALSO
 spanner help <subcommand> 
.SH BUGS
 file issues or bugs
.UR
https://opensource.sas.com/its
 
.SH AUTHORS
.B
 spanner
was written by SAS
.UR
http://www.sas.com/
.
.SH COPYRIGHT
 Copyright (c)
.B
SAS Institute Inc.
 
